### PR TITLE
Changelog for 3.0.22

### PR DESCRIPTION
**Pull request by talaj**
Hi @artemp! What about to release 3.0.22?

### CODE REVIEW

**Comment by artemp** [comment]
Hey @talaj HNY! Yes, sounds good, lets do it next week.

**Comment by talaj** [comment]
@artemp , can I help somehow?

**Comment by artemp** [comment]
@talaj - done 
https://mapnik.org/news/release-3.0.22
https://github.com/mapnik/mapnik/releases/tag/v3.0.22

**Comment by talaj** [comment]
Great! Thank you, @artemp!

**Pull request merged**
