### PR TITLE
Offset Algorithm Fixes and Reverse of Offset Direction.

### LINKED ISSUE #1382: offset_converter: Closed paths
offset_converter should try to produce a closed output path if the input path is closed.
Currently it leaves the path open or produces self intersections and fails for certain offsets.
img

### LINKED ISSUE #2851: Predictable offsetting on polygons
#2834 introduces a problematic back compatibility problem for cartographers using `line-offset` on polygons because it will potentially flip the side of the polygon that the offset occurs on.

This may be a serious blocker for people upgrading to Mapnik 3.0.0.

Let's brainstorm solutions...

 - maybe we could track if polygons have had their winding order flipped and then auto-adjust the offsetting direction?
 - ???

refs https://github.com/gravitystorm/openstreetmap-carto/issues/481 (a bug report for #1382 but also proof of people using offsetting on polygons)

### LINKED ISSUE #2895: Offset branch bug with multi-line text
The offset branch (https://github.com/mapnik/mapnik/compare/offset) has a regression with multi-line text. The text of:

```
Hello
World!
```

Now is displayed as:

```
World!
Hello
```

Before:

lines-5-400-400-1 0-agg-reference

After:

lines-5-400-400-1 0-agg

/cc @flippmoke

### PR DESCRIPTION
**Pull request by flippmoke**
Closes #1382
Closes #2851
Closes #2898
Closes #2895

### CODE REVIEW

**Comment by springmeyer** [comment]
@flippmoke are these test updates intended for being used against this branch? https://github.com/mapnik/test-data-visual/commit/70fc341ae3e70f52bc8c09115d3344692844cf88. If so then please keep those test updates in a corresponding branch of the `test-data-visual` repo.

**Comment by springmeyer** [comment]
Assigned to myself for review before merging.

**Comment by pnorman** [comment]
I'm having trouble building against this, what are the specific git hashes for the node modules mapnik and mapnik-vector-tile needed to be able to use this mapnik version?

**Comment by pnorman** [comment]
:shipit: 

Tested with a database of osm2pgsql-generated RHR polygons and behavior is now consistent with 2.2, as well as the expectation from ST_Buffer and similar that negative is to the inside of polygons.

**Comment by springmeyer** [comment]
I've reviewed this and it is an overall improvement in the consistently and predictability of offsets. So I concur with @pnorman. The only minor regression might be for users with styles that expect `line-offset` to be predictably on the left or right side. In this case users may need to flip the sign so `line-offset:5` would become `line-offset:-5`. All other changes are either extremely minor or clear improvements. To make the case here is a set of renderings over a variety of recent node-mapnik versions as we approached 3.0.0 (testcase from https://github.com/mapnik/test-data-visual/commit/efb81026fce780cf2731f02f3fb55f9096c3dff0):

### node-mapnik@1.4.1 / Mapnik 2.3.x

off-1 4 1

### with this branch:

off-3 3 1-offset

### mapnik 3.x previous to this fix/branch

off-3 3 1

**Comment by talaj** [comment]
@flippmoke - Is this change of the offset direction supposed to affect also lines, not just polygons? I'm asking because if you look into the [history of visual test for `verical-alignment`](https://github.com/mapnik/test-data-visual/commits/master/images/text-vertical-alignment-800-800-1.0-agg-reference.png), `bottom` and `top` values swapped meaning ([before](https://github.com/mapnik/test-data-visual/blob/8e70a97b35fdb687bbfe4027713e302b86e8420a/images/text-vertical-alignment-800-800-1.0-agg-reference.png), [after](https://github.com/mapnik/test-data-visual/blob/8551507f3b989fe482980e8c90281d15a5e64e07/images/text-vertical-alignment-800-800-1.0-agg-reference.png)) by this pull request, which is something worth notice in the the [notes for cartographers](https://github.com/mapnik/mapnik.github.com/blob/master/_posts/blog/2015-07-11-3.0-cartographer.md).

**Comment by springmeyer** [comment]
@talaj - yes - changed polygons so that `dy:negative` would be inward, and also changed lines such that a line with the same orientation as a polygon exterior ring (CCW) would be offset the same with `line-offset:negative`. I think I have this right (commenting from memory) /cc @flippmoke for confirmation. :+1: to being added to notes for cartographers.

**Comment by talaj** [comment]
Updates to notes for cartographers sent in https://github.com/mapnik/mapnik.github.com/pull/45.

**Pull request merged**
