### PR TITLE
alter extent of collision detector by layer's buffer-size

### PR DESCRIPTION
**Pull request by talaj**
Possible solution for https://github.com/mapnik/mapnik/issues/2517.

### CODE REVIEW

**Comment by springmeyer** [comment]
@talaj - had a chance to test more?

**Comment by talaj** [comment]
Yes, I had. There are some failing tests but I can only one consider a regression:

[`simple-shield.xml`](https://github.com/mapnik/mapnik/blob/master/tests/visual_tests/styles/simple-shield.xml) before:

simple-shield-600-400-1 0-agg-reference

after:

simple-shield-600-400-1 0-agg

It fails because these shields have list of placements `placements="N,S,E,W,SW,10,5"` and `N` position is rendered instead of `S`.

**Comment by springmeyer** [comment]
> I'm going to do some more tests in tiling environment.

Okay,great look forward to hearing about your findings.

**Comment by talaj** [comment]
https://github.com/mapnik/mapnik/issues/2929 seems like be the same problem with the same possible solution.

**Comment by talaj** [comment]
Replaced by https://github.com/mapnik/mapnik/pull/2949.

**Pull request closed without merging**
