### PR TITLE
fix labeling on polygons

### PR DESCRIPTION
**Pull request by talaj**
Text with `placement="line"` works only on `line_string` now.

This one definitely deserves visual test. I would merge it once visual tests are working.

### CODE REVIEW

**Comment by artemp** [comment]
@talaj  - good patch

**Comment by springmeyer** [comment]
> This one definitely deserves visual test. I would merge it once visual tests are working.

Agree. Here is a plan for integrating your work on C++ visual test runner: https://github.com/mapnik/mapnik/issues/2789#issuecomment-98001670

**Comment by springmeyer** [comment]
@talaj - I presume this is ready to land now that you've landed the visual tests?

**Comment by talaj** [comment]
I think polygon labeling is still buggy. See image in https://github.com/mapnik/test-data-visual/pull/4.

**Comment by talaj** [comment]
I have added commit that fixes problem with missing closing segment.
Before:
text-on-polygon-400-400-1 0-agg-reference
After:
text-on-polygon-400-400-1 0-agg-reference2

Tests covering this pull request are in https://github.com/mapnik/test-data-visual/pull/4

**Pull request merged**
