### PR TITLE
Simplify proj_transform_cache implementation 

### PR DESCRIPTION
**Pull request by artemp**
https://github.com/mapnik/mapnik/pull/4191#issuecomment-813377082

### CODE REVIEW

**Comment by artemp** [comment]
> although I do have an idea which I think is better than thread_local
@lightmare  what is it?

**Comment by mathisloge** [comment]
Have tested on windows. But I needed to move MAPNIK_DECL to the front. 
Normally both should work, but I think the recommended way is to write it before the return parameter. E.g. in this case it leads to a syntactically incorrect program.
```diff
diff --git a/include/mapnik/proj_transform_cache.hpp b/include/mapnik/proj_transform_cache.hpp
index 6bd8581fe..99486e0d5 100644
--- a/include/mapnik/proj_transform_cache.hpp
+++ b/include/mapnik/proj_transform_cache.hpp
@@ -31,8 +31,8 @@ namespace mapnik  {
 class proj_transform; // fwd decl
 namespace proj_transform_cache {

-void MAPNIK_DECL init(std::string const& source, std::string const& dest);
-proj_transform const* MAPNIK_DECL get(std::string const& source, std::string const& dest);
+MAPNIK_DECL void init(std::string const& source, std::string const& dest);
+MAPNIK_DECL proj_transform const* get(std::string const& source, std::string const& dest);

 } // namespace proj_transform_cache
 } // mamespace mapnik
```

But since these changes the demo/c++ application and the shared map benchmark are running smoothly. 

Note that the outputs are from a debug build.
```
Defaulting to max extent box2d(-10608803.2816615924239159,4028651.6142304763197899,-4323716.1968731693923473,10313738.6990188993513584)
    (pass --extent=<minx,miny,maxx,maxy> to restrict bounds)
"shared map"                                  4 workers    10 iters  19970 milliseconds      1 i/t/s
```

**Comment by artemp** [comment]
:+1: moving MAPNIK_DECL to the front is fine. I'll update master, thanks

**Comment by artemp** [comment]
6bab4e56fd591a530e6f020b9ad4fd1633823b40

**Comment by lightmare** [comment]
@artemp 
My idea may very well be another case of over-engineering, as I was pondering whether thread local cache is actually good, or just a quick stepping stone. I also haven't thought it through entirely, wish I found some time to try and implement it to see how it performs.

The benefit of thread local cache -- that each thread has its own -- is also a drawback: you can't use values computed by other threads. If you have multi-threaded rendering, chances are they use some common transforms. And if you have one thread that loads the map, and then passes it to worker threads that render tiles, the initialization of transforms in the loading thread is kinda wasted.

So that was my motivation: how to avoid constructing the same `proj_transform` in each thread without giving up concurrent construction of different transforms. It obviously requires synchronized access to the cache, and another map for keeping track of transforms currently under construction. To keep it relatively simple, I'm not going for out-of-order-construction of transforms.

It goes like this: acquire lockA, search the transform cache, if found return. Otherwise acquire lockB, release lockA, search the under-construction hashmap. If it contains a future for the key, wait for it to fulfil (lock released in wait), then return its value. Otherwise add a new future to the map, release lockB, construct the transform, re-acquire lockA, add transform to the cache map, acquire lockB, release lockA, fulfil the future, remove it from map, return. It's also doable with a single lock, but then a thread can hold the lock for up to 3 lookups (one being insertion), and it's not much simpler, so I prefer 2 locks.

**Comment by artemp** [comment]
@lightmare  thanks, looks like `thread_local` fits well here, unless there are some unforeseen issues. Avoiding dealing with locks is big plus I think.

**Pull request merged**
