### PR TITLE
Png8 encoding bug

### PR DESCRIPTION
**Pull request by sarametz**
Builds on PR #2599 
##### Hextree
Fixes bug where encoding a png32 with 2 non transparent pixels as png8 with hextree results in a fully transparent image
This caused a number of small changes to the visual test images
##### Octree
Fixes bug where encoding a png32 with 2 non transparent pixels as png8 with octree results in an image with 1x coloured pixel, 1x black pixel 
Images with at least one pixel with alpha less than 1 have their colours jumbled, as black was last in the palette rather than first. Two new tests have been added to show this.   
May be related to #1987, #1097, #2292

### CODE REVIEW

**Comment by rcoup** [comment]
@springmeyer @sarametz manually checked all the images here, but Travis is obviously running something slightly different. She's going to use #2662 to see if she can get a matching set of test failures/updates. And then we need to do the performance analysis.

**Comment by springmeyer** [comment]
How about you leave the image updates to me (so don't commit those changes for now). Then I'll confirm they pass and commit after merging.

**Comment by rcoup** [comment]
ok, so just drop the last commit from the PR and go back to 	f38d2ee? Easy As.

For benchmarks, how about "fastest time of 10x visual-test runs" for old vs new? And a file-size check via something like:
```bash
find /tmp/mapnik-visual-images -name "*.png" -printf '%s\n' | awk '{sum += $1} END{print sum}'
```

**Comment by springmeyer** [comment]
yes and yes

**Comment by sarametz** [comment]
| Without Changes | With Changes
---------- | ------------ | -------------
**Fastest Time** | 100.151s | 101.956s
**Average Time** | 101.748s | 103.668s
**Slowest Time** | 104.071s | 108.847s
**File Size Check** | 41190970 | 41380993   

Time: (min | mean | max) of all 1626 visual tests run 10x
Size check command: `find /tmp/mapnik-visual-images/ -name "*.png" -type f -exec ls -l {} \; | awk '{sum += $5} END {print sum}'`

**Comment by springmeyer** [comment]
Thanks for this detailed summary. I think ~1% is an acceptable increase given this fixes bugs. And hopefully we can make up the time other places like #2029. So I think its ready to merge and I will merge it once I have a chance to review and update the test images.

**Comment by springmeyer** [comment]
reminder to myself: also should try running `tests/python_tests/image_encoding_speed_test.py` to see if this detects any speed diffs

**Comment by springmeyer** [comment]
I applied the patch and made this change:

```diff
diff --git a/tests/python_tests/image_encoding_speed_test.py b/tests/python_tests/image_encoding_speed_test.py
index 9ba1748..999236d 100644
--- a/tests/python_tests/image_encoding_speed_test.py
+++ b/tests/python_tests/image_encoding_speed_test.py
@@ -72,7 +72,7 @@ def do_encoding():
         avg = (sum(set)/len(set))*1000
         name = func.__name__ + ' ' + format
         results[name] = [min_,avg,elapsed*1000,name,len(func())]
-        sortable[name] = [min_]
+        sortable[name] = [name]
 
     if 'blank' in tiles:
         def blank():
```

So that I could easily and quickly compare the output of that test before/after and could not see a significant change in perf (up to 3-4 ms change is just noise), so merging this now. Thanks!

**Pull request merged**
