### PR TITLE
Raster colorizer: check image bounds

### PR DESCRIPTION
**Pull request by talaj**
I think this is correct fix for https://github.com/mapnik/mapnik/pull/3872#issuecomment-375324545.

cc @flippmoke

### CODE REVIEW

**Comment by flippmoke** [comment]
@talaj do we want to merge this into `gdal_overview_fix_v3.0.x` and `gdal_overview_fix` branches first?

**Comment by talaj** [comment]
@flippmoke Not necessarily, but if it's more convenient for you, I can add the commit to those branches and close this pull request.

**Comment by flippmoke** [comment]
@talaj I am just wanting to make sure that we have a valid test for this prior. Do we hit this normally with out the changes in gdal_overview? I haven't had time to fully review the code around this change yet, but doing it right now.

**Comment by talaj** [comment]
@flippmoke There is no test which cover this in master currently. I will prepare one.

**Pull request merged**
