### PR TITLE
[CI] update vcpkg

### LINKED ISSUE #4362: update vcpkg in ci

### PR DESCRIPTION
**Pull request by mathisloge**
closes #4362

### CODE REVIEW

**Comment by artemp** [comment]
> @artemp this would be ready to merge. But I've updated the llvm toolchain to 15. This results in some other formatting. See the diff in the action: https://github.com/mapnik/mapnik/actions/runs/3518341002/jobs/5897145563

👍 thanks, I'll take a look tomorrow.

**Comment by artemp** [comment]
@mathisloge couple ideas - 

* should we disable formatting on third-party code e.g [catch.hpp](https://github.com/mapnik/mapnik/blob/master/test/catch.hpp) ? 

* would it be possible to update `.clang-format` to preserve original behaviour? New formatting is looking fine to me but I'd like it to be less strict.

**Comment by mathisloge** [comment]
> should we disable formatting on third-party code e.g [catch.hpp](https://github.com/mapnik/mapnik/blob/master/test/catch.hpp) ? 

Typically yes. but as it is in the source dir, I need to look into it how to exclude it. Generally I want to remove it and aquire it via cmake fetch content directly from github.  But I can only do that, as soon as the scons build is removed. 

> would it be possible to update .clang-format to preserve original behaviour? New formatting is looking fine to me but I'd like it to be less strict.

I need to look into it. Have reverted the change for now. So that the vcpkg pipeline can be run again

**Comment by mathisloge** [comment]
@artemp let us merge this first and I will then look into updating clang-format

**Review by artemp — APPROVED** [review]

**Pull request merged**
