### PR TITLE
Duplicate code elimination

### PR DESCRIPTION
**Pull request by talaj**

### CODE REVIEW

**Comment by flippmoke** [comment]
Saw title of pull request, figured it was my code. Confirmed. 👍 

@talaj 💯

**Comment by talaj** [comment]
What about this? @lightmare - can you please review/merge?

I know there are more duplicates like this, but take it as evolutionary step.

I can take a look on https://github.com/mapnik/mapnik/pull/3529 in return :).

I don't like this delayed pessimistic merge strategy. Say it's shit or merge asap.

**Comment by lightmare** [comment]
Looks good to me. Re-running travis now.

**Comment by talaj** [comment]
Thank you, @lightmare. I have removed that line and rebased.

**Comment by lightmare** [comment]
Hm, tried the [rebase and merge](https://help.github.com/articles/about-pull-request-merges/#rebase-and-merge-your-pull-request-commits) option, the doc says it's using fast-forward, i.e. shouldn't have created a new commit in this case, but it did :confused:

**Comment by flippmoke** [comment]
@talaj @lightmare 👍 you guys are awesome -- sorry for not just merging right away -- I have been away from the mapnik project some as of recently so don't want to step on any toes - so sorry for not merging myself.

**Pull request merged**
