### PR TITLE
fix scaling gray images

### PR DESCRIPTION
**Pull request by talaj**
This pull request is attempt to fix https://github.com/mapnik/mapnik/issues/3113 and https://github.com/mapnik/mapnik/issues/2902.

It's work in progress currently, mainly tests are missing.

### CODE REVIEW

**Comment by talaj** [comment]
Important question is whether to use `image_rgba8` for scaling or fix/modify AGG implementation of `gray32`.

**Comment by talaj** [comment]
Scaling colorized images seems to be no-go. Quality difference against proper fix is huge.

Here is bilinear scale with this pull request:
raster-scaling-bilinear-float-2-500-438-1 0-agg

This is "proper" fix in AGG from https://github.com/mapnik/mapnik/issues/3113#issuecomment-146878795:
raster-scaling-bilinear-float-2-500-438-1 0-agg-proper

This is current master:
raster-scaling-bilinear-float-2-500-438-1 0-agg-current

**Comment by talaj** [comment]
@artemp We should revert it, it wasn't ready. Or do you have some another plan with it?

**Comment by artemp** [comment]
@talaj - my bad :) please revert ^

**Pull request merged**
