### PR TITLE
Color font support improvements

### PR DESCRIPTION
**Pull request by talaj**
I tried to improve rendering with colored fonts. So far with AGG only, no halo yet. The main goal was to transform glyphs correctly to support line placement.

bitmap-color-font-2-512-512-1 0-agg-reference
bitmap-color-font-3-512-512-1 0-agg-reference

### CODE REVIEW

**Comment by springmeyer** [comment]
Wow, gorgeous renderings @talaj - nice work. I'm 👍  on merging assuming that no other visual tests are impacted. Which appears to be the case based on https://github.com/mapnik/test-data-visual/pull/52/files 👍  Although I do notice that the grid_renderer might need an update.

**Comment by talaj** [comment]
I have updated the grid_renderer:
bitmap-color-font-1-256-256-1 0-grid-reference
Halo is also supported with `halo-rasterizer="fast"`:
bitmap-color-font-1-256-256-1 0-agg-reference

**Comment by talaj** [comment]
> I'm 👍 on merging assuming that no other visual tests are impacted.

No existing tests are impacted, only new added.

**Comment by artemp** [comment]
@talaj - seeing one related visual test is failing on OSX: https://travis-ci.org/mapnik/mapnik/jobs/274968777

**Comment by talaj** [comment]
Hm, it's Cairo and only 14 different pixels. I don't have OSX to reproduce it.

I'm thinking about disabling that test for Cairo. Maybe disabling text-halo in that test could help.

**Comment by artemp** [comment]
I'm also getting segfault on linux (ubuntu 17.04) compiled with `clang++6/libstdc++.so.6`
+1 for disabling for Cairo 

```
(gdb) r
Starting program: /home/artem/projects/mapnik/test/visual/run 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
.............................................................................................................run: cairo-scaled-font.c:459: void _cairo_scaled_glyph_page_destroy(cairo_scaled_font_t *, cairo_scaled_glyph_page_t *): Assertion `!scaled_font->cache_frozen' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff329b77f in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff329b77f in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff329d37a in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff3293b47 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff3293bf2 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff6355844 in _cairo_scaled_glyph_page_destroy (scaled_font=0x86d990, page=0xa24480) at cairo-scaled-font.c:459
#5  0x00007ffff6358560 in _cairo_scaled_font_free_last_glyph (scaled_font=0x86d990, scaled_glyph=<optimised out>)
    at cairo-scaled-font.c:2924
#6  0x00007ffff6357329 in _cairo_scaled_glyph_lookup (scaled_font=0x86d990, index=<optimised out>, 
    info=CAIRO_SCALED_GLYPH_INFO_PATH, scaled_glyph_ret=0x7fffffff9e40) at cairo-scaled-font.c:3038
#7  0x00007ffff6357b7f in _cairo_scaled_font_glyph_path (scaled_font=0x86d990, glyphs=0x7fffffff9ee0, 
    num_glyphs=<optimised out>, path=0x7482e8) at cairo-scaled-font.c:2659
#8  0x00007ffff632289b in _cairo_gstate_glyph_path (gstate=0x748148, glyphs=0x7fffffffa740, num_glyphs=0, path=<optimised out>)
    at cairo-gstate.c:2090
#9  0x00007ffff63154a7 in cairo_glyph_path (cr=0x747f80, glyphs=0x7fffffff9ab0, num_glyphs=0) at cairo.c:3552
#10 0x00007ffff73ee89b in mapnik::cairo_context::glyph_path (this=0x7fffffffb950, index=8, pos=...)
    at src/cairo/cairo_context.cpp:431
#11 0x00007ffff73eec3f in mapnik::cairo_context::add_text (this=0x7fffffffb950, pos=..., manager=..., comp_op=mapnik::src_over, 
    halo_comp_op=mapnik::src_over, scale_factor=1) at src/cairo/cairo_context.cpp:471
#12 0x00007ffff73f6658 in mapnik::cairo_renderer<std::shared_ptr<_cairo> >::process (this=0x7fffffffb940, sym=..., feature=..., 
    prj_trans=...) at src/cairo/process_text_symbolizer.cpp:99
#13 0x00007ffff6d9671d in mapnik::process_impl<true>::process<mapnik::cairo_renderer<std::shared_ptr<_cairo> >, mapnik::text_symbolizer, mapnik::feature_impl, mapnik::proj_transform> (ren=..., sym=..., f=..., tr=...)
    at include/mapnik/symbolizer_dispatch.hpp:43
#14 0x00007ffff6d9662b in mapnik::symbolizer_dispatch<mapnik::cairo_renderer<std::shared_ptr<_cairo> > >::operator()<mapnik::text_symbolizer> (this=0x7fffffffb208, sym=...) at include/mapnik/symbolizer_dispatch.hpp:82
#15 0x00007ffff6d9656e in mapbox::util::detail::dispatcher<mapnik::symbolizer_dispatch<mapnik::cairo_renderer<std::shared_ptr<_cairo> > >, mapbox::util::variant<mapnik::point_symbolizer, mapnik::line_symbolizer, mapnik::line_pattern_symbolizer, mapnik::polygon_symbolizer, mapnik::polygon_pattern_symbolizer, mapnik::raster_symbolizer, mapnik::shield_symbolizer, mapnik::text_symbolizer, mapnik::building_symbolizer, mapnik::markers_symbolizer, mapnik::group_symbolizer, mapnik::debug_symbolizer, mapnik::dot_symbolizer>, void, mapnik::text_symbolizer, mapnik::building_symbolizer, mapnik::markers_symbolizer, mapnik::group_symbolizer, mapnik::debug_symbolizer, mapnik::dot_symbolizer>::apply_const(mapbox::util::variant<mapnik::point_symbolizer, mapnik::line_symbolizer, mapnik::line_pattern_symbolizer, mapnik::polygon_symbolizer, mapnik::polygon_pattern_symbolizer, mapnik::raster_symbolizer, mapnik::shield_symbolizer, mapnik::text_symbolizer, mapnik::building_symbolizer, mapnik::markers_symbolizer, mapnik::group_symbolizer, mapnik::debug_symbolizer, mapnik::dot_symbolizer> const&, mapnik::symbolizer_dispatch<mapnik::cairo_renderer<std::shared_ptr<_cairo> > >&&) (v=..., f=<unknown type in /opt/mapnik/lib/libmapnik.so.3.1, CU 0x334c26, DIE 0x3ac3d3>)
    at deps/mapbox/variant/include/mapbox/variant.hpp:327
```

**Comment by talaj** [comment]
OK, I will disable it. I've also got that abort when compiled against Cairo library from my Debian system:

```
 $ test/visual/run --cairo -s 1 bitmap-color-font-3
run: ../../../../src/cairo-scaled-font.c:459: _cairo_scaled_glyph_page_destroy: Assertion `!scaled_font->cache_frozen' failed.
[1]    10182 abort      test/visual/run --cairo -s 1 bitmap-color-font-3
```

When I was trying to make color fonts work with Cairo by passing `FT_LOAD_COLOR ` to `cairo_ft_font_face_create_for_ft_face()`, I've got this:

```
 $ test/visual/run --cairo -s 1
...........................................................................
  what():  cairo: invalid value for an input cairo_format_t
.[1]    2103 abort      test/visual/run --cairo -s 1
```
Which may mean Cairo of version I was using doesn't understand BGRA format of the color glyph bitmap.

**Comment by talaj** [comment]
Nice thing about Cairo is that text halo is working out of the box for bitmap fonts because Cairo can trace vectorial outline of a bitmap glyph!

**Pull request merged**
