### PR TITLE
restrict barewords (unquoted strings) in expression grammar

### PR DESCRIPTION
**Pull request by lightmare**
It's not barewords per se that break the logical `not` operator, it's [this line](https://github.com/mapnik/mapnik/commit/6a51c6e7f6fe784d93332fd48657b2dde77ce020#diff-1e2ad6c59a4d7152bb76fc8547a9a796L191) actually -- `not expr` is not a `primary_expr`, this line makes `not x op y` be parsed as `not (x op y)`, in other words, giving `not` the lowest possible precedence.

But as I wrote in #3214, barewords are not future-proof, their use should be restricted and it's easier to just remove them.

Btw, in current master, this check passes:
```c++
TRY_CHECK(eval(" not not = not not ") == true);
```
The expression is parsed as `not ('not' = not 'not')`. The first `not` is grabbed by the evil line I linked above, the second is tried by that line, but `= not not` fails to match `expr` so it backtracks and matches `ustring`. The third `not` is grabbed by the evil line again, and the last by `ustring`. The second alternative in the `not_expr` rule higher in the grammar is never used.

### CODE REVIEW

**Comment by lightmare** [comment]
There's one failing unit test which I think might be a typo in the test: @flippmoke can you check the `dy="t"`here? https://github.com/mapnik/test-data/commit/3b1f481ac2ceeb780255cd4c76a42ae06197b9bc#diff-2f6d1bb7f324e0d6a35ca20c7023f5beR18

Then there are 5 visual tests that actually rely on parsing bareword `bar` as a string:
`bar` in [test/data-visual/styles/group-symbolizer-line-2.xml](https://github.com/mapnik/test-data-visual/blob/f5623b5a312c58cd9c1926008fcf114944c769a3/styles/group-symbolizer-line-2.xml)
`bar` in [test/data-visual/styles/group-symbolizer-line-avoid-edges.xml](https://github.com/mapnik/test-data-visual/blob/f5623b5a312c58cd9c1926008fcf114944c769a3/styles/group-symbolizer-line-avoid-edges.xml)
`bar` in [test/data-visual/styles/group-symbolizer-line-minimum-padding.xml](https://github.com/mapnik/test-data-visual/blob/f5623b5a312c58cd9c1926008fcf114944c769a3/styles/group-symbolizer-line-minimum-padding.xml)
`label` in [test/data-visual/styles/multipolygon-centroid-postgis.xml](https://github.com/mapnik/test-data-visual/blob/f5623b5a312c58cd9c1926008fcf114944c769a3/styles/multipolygon-centroid-postgis.xml)
`XX` in [test/data-visual/styles/formatting-expr-alignment.xml](https://github.com/mapnik/test-data-visual/blob/f5623b5a312c58cd9c1926008fcf114944c769a3/styles/formatting-expr-alignment.xml)

And 1 where I think `[label]` was intended instead:
`label` in [test/data-visual/styles/multipolygon-centroid-wkt.xml](https://github.com/mapnik/test-data-visual/blob/f5623b5a312c58cd9c1926008fcf114944c769a3/styles/multipolygon-centroid-wkt.xml)

**Comment by lightmare** [comment]
So, if you want to really want to keep barewords in the grammar, I suggest restricting them to single-term expressions only, never inside complex expressions with operators, i.e.:
```c++
expr = logical_expr | ustring;
```
What do you think?

**Comment by artemp** [comment]
>```c++
expr = logical_expr | ustring;
```
^  I like this variant

**Comment by lightmare** [comment]
@artemp ok I'll redo the pull. One more question, as my previous suggestion:
> single-atom expressions only, never inside complex expressions with operators

Isn't equivalent to this grammar:
```
expr = logical_expr | ustring;
```
Since `expr` is used recursively in:
 - `unary_function_expr`
 - `binary_function_expr`
 - `'(' >> expr >> ')'`

This grammar will actually accept:
`(foo) + (bar) == "foobar"` -- both `foo` and `bar` will match `ustring` in parenthesized `expr`
`max(foo, bar) == max("foo", "bar")`

That means parentheses will be alternative string-quotes. Is that okay, or should I go with *single-atom expressions only*?

**Comment by artemp** [comment]
@lightmare - Thanks, I think we should go for `single-atom` expressions as it's conceptually cleaner and will allow easily drop unquoted string support in the future.

**Comment by lightmare** [comment]
Just realized one more change might be needed.
```c++
unary_function_expr = unary_func_type > lit('(') > logical_expr > lit(')');
```
The expectation operator `>` before the opening parentheses will prevent using a function name as a bareword. Currently `log` matches unquoted string, but if the `log` function is added in the future, it will be an error. However, as there is no ambiguity, changing the first expectation to `>>` shouldn't hurt, and won't break single-word expressions when functions are added.

**Comment by artemp** [comment]
@lightmare - looking good, going to port to https://github.com/mapnik/mapnik/tree/spirit-x3

**Pull request merged**
