### PR TITLE
visual tests: set number of parallel threads by JOBS environment variable

### PR DESCRIPTION
**Pull request by talaj**
Speed up visual tests.

### CODE REVIEW

**Comment by springmeyer** [comment]
Do you think we should run tests in parallel by default?

**Comment by talaj** [comment]
Why not? In most cases one wants to run them as fast as possible. It also might uncover some concurrency problems.

**Comment by talaj** [comment]
Maybe use some another variable, `TEST_JOBS`...

**Comment by springmeyer** [comment]
I think manually setting JOBS is fine for now.

**Pull request merged**
