### PR TITLE
add text upright auto-down

### PR DESCRIPTION
**Pull request by talaj**
Implements https://github.com/mapnik/mapnik/issues/2635. Adds missing test for `upright` property.

### CODE REVIEW

**Comment by herm** [comment]
Looks good to me.

**Comment by talaj** [comment]
Rebase and merge when green?

**Comment by springmeyer** [comment]
Can you create a pull at https://github.com/mapnik/mapnik-reference with update docs for this property? Ideally provide a much detail as you can on all the options while you are updating. Then I think this is ready to merge. Great work @talaj.

**Comment by talaj** [comment]
https://github.com/mapnik/mapnik-reference/pull/95 created. Merge?

**Comment by springmeyer** [comment]
:+1: merge

**Comment by gagecarto** [comment]
I am trying to use  text-upright: auto-down;  in MapBox studio 0.2.6 and not seeing a response in the labels on lines. 

text-upright: left and text-upright:right; are working but I don't see anything change with auto-down

**Comment by talaj** [comment]
@gagecarto I think there is version mismatch of `mapnik` and `mapnik-reference` in MapBox studio 0.2.6 package. `auto-down` is quite new feature and didn't get into MapBox studio release yet.

**Pull request merged**
