### PR TITLE
png8 hextree/octree encoding produces blank output

### PR DESCRIPTION
**Pull request by rcoup**
Test case:
* png32 image that has 2x non-transparent pixels
* encoding as png8 with hextree results in a fully transparent image
* encoding as png8 with octree results in an image with 1x coloured pixel, 1x black pixel
* expected: output images resemble the input image

May be related to #1987, #1097, #2292

### CODE REVIEW

**Comment by craigds** [comment]
This line appears to be the cause of the hextree issues at least:

https://github.com/mapnik/mapnik/blob/2.3.x/include/mapnik/hextree.hpp#L411

Replacing that with:

    if (itr->count != 0)

... I see the correct output.


test script:

    import mapnik

    img = mapnik.Image(256, 256)
    img.background = mapnik.Color("transparent")

    img.set_pixel(250, 250, mapnik.Color(255, 1, 1, 255))
    img.set_pixel(251, 250, mapnik.Color(1, 1, 255, 255))

    img.save("test-pr2599-1.png","png")
    img.save("test-pr2599-2.png","png8:m=h")
    img.save("test-pr2599-3.png","png8:m=h:g=1.0")
    img.save("test-pr2599-4.png","png8:m=o")

Looks like this was previously attempted in https://github.com/mapnik/mapnik/commit/03250869b642cf9de71d02e72abf0048fe7c8855 but was rejected for some reason?

**Comment by springmeyer** [comment]
@craigds the reason it never landed was 1) uncertainty it was needed (because the crash we were trying to avoid was no longer replicable https://github.com/mapnik/mapnik/issues/2068), 2) concern (untested) that it would slow down encoding (needs testing), and 3) unclear it was worth it in that we'd need to update a lot of visual tests for no huge benefit.

So, if you can demonstrate no perf hit, you think its a good change, and review/update the visual tests then I think it would make sense to get into master.

**Comment by craigds** [comment]
I can't demonstrate no perf hit. On the contrary, I can demonstrate that some images are much bigger and also take longer to write.

[This script](https://gist.github.com/craigds/d0c7ba50426ee159322a) shows the worst case (all pixels are random, so the palette is filled up).

with current trunk code:

> 7.714s for 20000 trials
> 97 bytes

with `if (itr->count != 0)`:

> 12.408s for 20000 trials
> 1345 bytes

Then feeling dejected at the bad performance, I noticed that the output image is actually completely empty for the current trunk, since *all* the palette entries are stripped. So .. for any images that this makes bigger/slower, it also fixes problems in.

**Comment by rcoup** [comment]
@springmeyer any further thoughts here? If you're ok with changing it we can trawl through the visual tests and update them. What's the best approach for testing performance in this area?

**Comment by springmeyer** [comment]
> So it seems likely that for any images that this makes bigger/slower, it also fixes problems in.

Interesting.

> If you think it'd be helpful, I suppose I could look into making this a configurable parameter, i.e. "png8:m=h,n=3".

If you think the only perf hit is with images it "fixes" then ideally we don't expose yet another parameter.

> What's the best approach for testing performance in this area?

The visual tests all use png8 - what about using them as a real-world case? Do they run measurably slower with the change? Also would be good to take a look at the timings in https://github.com/mapnik/mapnik/blob/master/tests/python_tests/png_encoding_test.py and make sure they don't slow down.

**Comment by springmeyer** [comment]
closed as #2671 landed.

**Pull request closed without merging**
