### PR TITLE
Fix situation where offset_converter might start off with an SEG_END …

### PR DESCRIPTION
**Pull request by flippmoke**
…from the vertex, therefore starting invalid processing. Tests added to confirm fix. Ref #2937

### CODE REVIEW

**Comment by pnorman** [comment]
I'm getting a rendering bug with this. This is without text-spacing or similar, so it is rendering.

image

Currently tracking down if it's in this PR, or also present in master

**Comment by pnorman** [comment]
Bug is not caused by this PR

**Comment by springmeyer** [comment]
@flippmoke - my understanding is that this pull was created as a guess of what the problem was in #2937. Now that you've fixed the real issue behind #2937 should this be discarded or still has value in being applied?

**Comment by springmeyer** [comment]
per chat @flippmoke says still worthy to apply.

**Pull request merged**
