### PR TITLE
Fix centroid and interior algorithms

### PR DESCRIPTION
**Pull request by talaj**
Should solve https://github.com/mapnik/mapnik/issues/3539, https://github.com/mapnik/mapnik/issues/3558, https://github.com/mapnik/mapnik/issues/3550.

I found that closing segment was not handled correctly in both algorithms.

All misplaced centroids and interiors I have tried so far are fixed.

### CODE REVIEW

**Comment by artemp** [comment]
thanks @talaj !

**Comment by sommerluk** [comment]
Thanks a lot!

**Comment by pnorman** [comment]
Will this be in 3.0.13, or will it be only 3.1.x?

**Comment by kocio-pl** [comment]
Does anybody know what is the release plan? For me this is important bugfix (labels placing is essential for many maps), but still just a fix, so I guess it fits 3.0.16. I hope such a small change could be released in not so distant future, especially since [3.0.15 was released 4 months ago](https://github.com/mapnik/mapnik/releases/tag/v3.0.15).

**Comment by artemp** [comment]
> Will this be in 3.0.13, or will it be only 3.1.x? 

It can't be in `3.0.13`  - it has been released already. I'm planning to backport to `3.0.x` and we can start preparing for `3.0.16` release.

/cc @pnorman

**Pull request merged**
