### PR TITLE
v3.0.x: True global pattern alignment, fixed local alignment

### PR DESCRIPTION
**Pull request by talaj**
A port of https://github.com/mapnik/mapnik/pull/3989 to v3.0.x.

### CODE REVIEW

**Comment by sommerluk** [comment]
Quick test:

Kubuntu 19.04, Mapnik 3.0.22, CartoCSS 1.2.0. Relevant code:

```cartocss
      polygon-pattern-file: url('symbols/wetland_mangrove.png');
      polygon-pattern-alignment: global;
```

The test image is 200 px x 200 px:

wetland_mangrove

The result is still no global alignment:

rendering

What am I doing wrong?

**Comment by talaj** [comment]
I've tried Mapnik 3.0.22 from Ubuntu 19.04 and the test of global pattern alignment is passing.

Is your Kosmtik using that version of Mapnik? If I do `npm install kosmtik`, the log shows that Mapnik 3.0.20 is used.

**Comment by sommerluk** [comment]
Hm, I'm installing Kosmtik from the current Master branch at Github.

When looking into the node_modules folder, it seems that it uses mapnik 4.2.1, mapnik-pool 0.1.3, mapnik-reference 8.10.0, mapnik-vector-tile 2.2.1, carto 1.2.0 (info taken from the package.json file within the corresponding folders).

When running kosmtik, I see:

```cartocss
[Core] Generating Mapnik XML…
[Core] Using mapnik version 3.1.0
```

Anyway: If I'm using the new `line-pattern-type: repeat;` for road rendering (which was introduced in Mapnik 3.0.22), that works. So I suppose that Kosmtik is running correctly Mapnik 3.0.22. Here a screenshot that shows both, the working `line-pattern-type: repeat;` on a road together with the non-working global alignment on

```cartocss
[int_wetland = 'mangrove'] {
      polygon-pattern-file: url('symbols/wetland_mangrove.png');
      polygon-pattern-alignment: global;
    }
```

(Using as wetland_mangrove.png the above shown example file.)

Screenshot_20190423_172638

When filtering the CartoCSS output, the following rules mention the wetland_mangrove.png image file:


```xml
    <Rule>
      <MaxScaleDenominator>100000</MaxScaleDenominator>
      <Filter><![CDATA[([natural] = 'shoal') and ([int_wetland] = 'mangrove')]]></Filter>
      <PolygonPatternSymbolizer alignment="global" file="symbols/wetland_mangrove.png" />
    </Rule>

    <Rule>
      <MaxScaleDenominator>100000</MaxScaleDenominator>
      <Filter><![CDATA[([natural] = 'beach') and ([int_wetland] = 'mangrove')]]></Filter>
      <PolygonPatternSymbolizer alignment="global" file="symbols/wetland_mangrove.png" />
    </Rule>

    <Rule>
      <MaxScaleDenominator>100000</MaxScaleDenominator>
      <Filter><![CDATA[([int_wetland] = 'mangrove') and ([natural] = 'reef')]]></Filter>
      <PolygonPatternSymbolizer alignment="global" file="symbols/wetland_mangrove.png" />
    </Rule>

    <Rule>
      <MaxScaleDenominator>100000</MaxScaleDenominator>
      <Filter><![CDATA[([int_wetland] = 'mangrove')]]></Filter>
      <PolygonPatternSymbolizer alignment="global" file="symbols/wetland_mangrove.png" />
    </Rule>
```

**Comment by talaj** [comment]
@sommerluk Thank you for the info. I will try to figure it out.

**Comment by sommerluk** [comment]
Attaching a python script that calls Mapnik.

[render_single_tile_multiple.py.txt](https://github.com/mapnik/mapnik/files/3111744/render_single_tile_multiple.py.txt)

When using this script to produce PNG tiles, than global alignment works correctly!

**Comment by talaj** [comment]
I think it's due to Mapnik 3.1.0 which is being installed from NPM. That version does not contain the pattern alignment fix. I haven't had time to confirm that yet.

**Comment by sommerluk** [comment]
There is a command line option for kosmtik:
```
--mapnik-version   Optional mapnik reference version to be passed to Carto  [3.1.0]
```

When calling kosmtik, with `--mapnik-version 4.2.1` or `--mapnik-version 3.0.22` than I see the corresponding version on the terminal, but the global alignment does not work either.

What seems strange is that at the same time, `line-pattern-type: repeat;` works correctly though it's also a new feature in 3.0.22.

**Comment by talaj** [comment]
node-mapnik 4.2.1 is unfortunately built with Mapnik just one commit before the pattern alignment fix:
https://github.com/mapnik/node-mapnik/blob/321ee2791189ae36eb05bb26226cdfed9ec24dcf/package.json#L8

`add "clipPath" to unsupported elements` is the commit `da69fdf66`:
https://github.com/mapnik/mapnik/commits/7dcf5ee0826e41f3c4ae378dd094ad7942fb435d

So new release of node-mapnik is needed.

**Comment by sommerluk** [comment]
Thanks for investigation!

**Pull request merged**
