### PR TITLE
v3.0.x: Line pattern "repeat"

### PR DESCRIPTION
**Pull request by talaj**
Port of https://github.com/mapnik/mapnik/pull/3980 to v3.0.x.

### CODE REVIEW

**Comment by sommerluk** [comment]
@talaj Thanks for the port!

**Comment by sommerluk** [comment]
@nebulon42 This PR adds more options to an existing symbolizer. To use it in CartoCSS, would it work right out of the box? Or does it require also an update of https://github.com/mapnik/mapnik-reference/ ? Or does it require even a new CartoCSS release?

**Comment by talaj** [comment]
@sommerluk I've prepared https://github.com/mapnik/mapnik-reference/pull/153 for that.

**Comment by sommerluk** [comment]
@talaj That’s great! Thanks.

**Comment by nebulon42** [comment]
Yes, it would need an update of mapnik-reference as @talaj already pointed out. It also requires a new carto release if mapnik-reference increases its version in a way that is not covered by the pattern in the [package.json](https://github.com/mapbox/carto/blob/master/package.json#L40). The pattern is ~ so that means that whenever mapnik-reference goes to 8.10.x we need a new release there. This should, however, not influence the versioning decisions. This change, according to semver, would IMO require to go to 8.10.0. A carto release is not much work, it would be a patch release, even if its impact is a bit larger.

**Comment by sommerluk** [comment]
@talaj Could you also update the [npm package](https://www.npmjs.com/package/mapnik-reference) (currently 8.9.2)?

**Comment by talaj** [comment]
@sommerluk, yes, I'm going to do that.

**Comment by talaj** [comment]
@sommerluk Just published [mapnik-reference 8.10.0](https://www.npmjs.com/package/mapnik-reference/v/8.10.0).

**Comment by sommerluk** [comment]
@talaj That’s great, thanks!

**Pull request merged**
