### PR TITLE
marker direction

### PR DESCRIPTION
**Pull request by talaj**
This is attempt to bring `upright` property to markers symbolizer which should solve https://github.com/mapnik/mapnik/issues/2374 and https://github.com/mapnik/mapnik/issues/1030.

I was thinking about reusing upright property for text but there is almost empty intersection between values for text and markers. It is also useful to set default values for text and markers separately.

### CODE REVIEW

**Comment by talaj** [comment]
Rebased. I have changed naming and added `up` and `down` values inspired by https://github.com/mapnik/mapnik/issues/2635:
markers-upright

**Comment by springmeyer** [comment]
@talaj - looks fantastic and a great contribution. What do you think about

 - auto-down behavior as well (so the inverse of `auto`)?
 - I just merged group symbolizer support for markers - can you rebase again and make sure your changes play well with groups?
 - Would you be up for tackling #2635 as well so we can keep markers and text in sync as much as possible. Now that markers are supported in groups the support for placing text and markers together will be very commonly used so I think trying to keep implementations and properties close will be beneficial.

**Comment by talaj** [comment]
* I have added `auto-down` value.
* It's rebased.
* Yes, I can take a look on https://github.com/mapnik/mapnik/issues/2635. If we can look at markers as a special case of text with just one character, then markers and text can have exactly the same upright properties.

**Comment by talaj** [comment]
@springmeyer - Is it ok?
markers-upright

**Comment by springmeyer** [comment]
@talaj renderings look fantastic. Can you explain what left/right/left_only/right_only would do? I've never fully understood those options for text.

Also, I'm starting to wonder if we should use a better name than `marker-upright`? I wonder if `marker-direction` or `marker-orientation` would be better?

If we do settled on better naming/design for markers then I think we could implement the new name for text as well and then deprecate `text-upright`.

**Comment by talaj** [comment]
@springmeyer 
This is reference image for test I have created for https://github.com/mapnik/mapnik/issues/2635. It should explain how all `upright` options work. Those lines go clockwise.
text-upright-800-800-1 0-agg

If there is better name for this functionality then I will use it.

**Comment by talaj** [comment]
So I introduced `orientation` property instead of `upright` for markers since the functionality is not only about setting markers upright. It behaves almost exactly the same as `upright` for text, except of:
* Default value is `right` instead of `auto`.
* There are two more values `up` and `down`.
marker-orientation-1152-384-1 0-agg-reference

**Comment by springmeyer** [comment]
I propose `marker-direction` because `text-orientation` property also/already exists and it accepts degrees rather than being an enum. What do you think?

Over this is looking great - glad to see travis is green - thanks for the hard work.

**Comment by talaj** [comment]
I agree with `marker-direction`.

**Comment by talaj** [comment]
Rebased with name `marker-direction`. Created pull request in mapnik-reference: https://github.com/mapnik/mapnik-reference/pull/96.

**Comment by talaj** [comment]
Any chance to merge this?

**Comment by artemp** [comment]
@talaj - thanks!

**Pull request merged**
