### PR TITLE
Test for geojson with multiple different properties across features

### PR DESCRIPTION
**Pull request by mapsam**
This adds a unit test to ensure GeoJSON `FeatureCollections` with multiple, different properties across `Features` are not lost. This test is a WIP, since it currently validates the error where [all field names are not reported](https://github.com/mapbox/mapnik-omnivore/issues/127). See the [`if/else`](https://github.com/mapnik/mapnik/blob/7a98745883cab62fbe9619dca7362e268accb1c8/test/unit/datasource/geojson.cpp#L669-L678) checking for the correct properties depending on `cache_features == false && create_index == false`.

**Next steps**: require using indexes for GeoJSON and update this test accordingly

Could use some :eyes: from @springmeyer and possibly some further clarification on "next steps"

### CODE REVIEW

**Comment by springmeyer** [comment]
Excellent @mapsam. Thanks for this test. The **Next Step** you listed is a great workaround for users that hit this: use indexes. The other **Next Step** I see is to discuss whether this is fixable - we can do this over at #3238.

As far as this test: I see things are passing fine on travis (don't worry about the timed out OSX coverage job which is unrelated to your pull), so please merge this whenever you are ready.

**Comment by springmeyer** [comment]
Merged https://github.com/mapnik/test-data/pull/6 and will merge this now. Thanks @mapsam!

**Comment by mapsam** [comment]
> so please merge this whenever you are ready

Didn't see this - thanks for merging @springmeyer !

**Comment by artemp** [comment]
As explained in #3238  - disk index queries first five features, other modes only first one.
Test file only has two features which is not sufficient

/cc @mapsam @springmeyer 

```json
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {
                "one": 1
            },
            "geometry": {
                "type": "Point",
                "coordinates": [0, 0]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "two": 2
            },
            "geometry": {
                "type": "Point",
                "coordinates": [1, 1]
            }
        }
    ]
}
```

**Comment by springmeyer** [comment]
@artemp thanks for the heads up on this, let's discuss over at #3238

**Pull request merged**
