### PR TITLE
Multi part shapeindex

### PR DESCRIPTION
**Pull request by artemp**
Ready to merge when https://github.com/mapnik/mapnik/issues/3216 is closed

### CODE REVIEW

**Comment by springmeyer** [comment]
One thing I noticed related to this feature. If I run the python-mapnik tests I see a failure like:

```
======================================================================
FAIL: python_tests.reprojection_test.test_visual_zoom_all_rendering4
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dane/Library/Python/2.7/lib/python/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/dane/projects/python-mapnik/test/python_tests/reprojection_test.py", line 105, in test_visual_zoom_all_rendering4
    'test/python_tests/' + expected))
AssertionError: failed comparing actual (/tmp/mapnik-merc2merc-reprojection-render2.png) and expected (test/python_tests/images/support/mapnik-merc2merc-reprojection-render2.png)

----------------------------------------------------------------------
Ran 509 tests in 14.475s
```

After generating indexes before running the tests like: `shapeindex --index-parts test/data/shp/*shp`.

It looks like a few polygons are being dropped which leads to the test failure. Diff image is:

diff

**Comment by artemp** [comment]
@springmeyer - hmm I seemed to get
```
python_tests.reprojection_test.test_visual_zoom_all_rendering1 ... ok
python_tests.reprojection_test.test_visual_zoom_all_rendering2 ... ok
python_tests.reprojection_test.test_visual_zoom_all_rendering3 ... ok
python_tests.reprojection_test.test_visual_zoom_all_rendering4 ... ok
```

Did something got out-of-sync in `test/data` ?

**Comment by artemp** [comment]
disregard the above - replicated and needs fixing 
```
python_tests.reprojection_test.test_visual_zoom_all_rendering4 ... FAIL
```
/cc @springmeyer

**Comment by artemp** [comment]
```
BUFFERED EXT:box2d(-28658688.3988907560706139,-21594384.3132049404084682,28658688.3988907560706139,31681814.3319715298712254)
LAYER EXT:box2d(-17195213.0393344499170780,-8283343.6938823731616139,17195213.0393344499170780,18365151.3630704432725906)
LAYER EXT 2:box2d(-20037508.3399999998509884,-8283343.6938823731616139,20037508.3399999998509884,18365151.3630704432725906)
```
It turned out to be an issue with how BBOX query extent is calculated when `maximum_extent` is not set. `LAYER_EXT` is smaller then it should be after re-projection/clipping. With '--index-parts` options individual polygons near W/E borders are failing intersection test.

**Comment by springmeyer** [comment]
@artemp - so you are saying this is not a problem with `--index-parts` but rather a longstanding bug? If that is so, can you create a new issue to track the problem? (Can you think of a simplier testcase to get at the bug?)

**Comment by artemp** [comment]
@springmeyer - yes, exactly, this is separate from '--index-parts'. I'll create a separate ticket.

**Comment by artemp** [comment]
New ticket https://github.com/mapnik/mapnik/issues/3226

**Pull request merged**
