### PR TITLE
Building symbolizer improvements

### PR DESCRIPTION
**Pull request by talaj**
Refs https://github.com/mapnik/mapnik/issues/3502.

Unifies unit of `height` property of building symbolizer with [documentation](https://github.com/mapnik/mapnik-reference/blob/77f1902638ff61a4ad6d16f07023ef1042a60500/3.0.6/reference.json#L2564) to pixel.

The code is simplified, [include/mapnik/segment.hpp](https://github.com/mapnik/mapnik/blob/8c6bf0eef67cbf97f717bc388424d0dc5cf0c037/include/mapnik/segment.hpp) is no longer required and is removed. All building faces have the same color, they don't have to be [sorted](https://github.com/mapnik/mapnik/blob/8c6bf0eef67cbf97f717bc388424d0dc5cf0c037/include/mapnik/renderer_common/process_building_symbolizer.hpp#L69).

It also has some performance improvement.

```
 $ test/visual/run --agg -s 1 -i 1000 -d building-symbolizer-2 building-symbolizer-1
..
Visual rendering: 0 failed / 2 passed / 0 overwritten / 0 errors
agg:    8813 milliseconds
total:  8813 milliseconds
```

```
 $ test/visual/run --agg -s 1 -i 1000 -d building-symbolizer-2 building-symbolizer-1
..
Visual rendering: 0 failed / 2 passed / 0 overwritten / 0 errors
agg:    7866 milliseconds
total:  7866 milliseconds
```

### CODE REVIEW

**Comment by lightmare** [comment]
Is there a reason this wasn't merged? Looks good to me, conflicts are easy to resolve, they're not in code.

**Comment by lightmare** [comment]
Possibly fixes #1498

**Comment by lightmare** [comment]
@talaj Sorry I messed up. I was wondering why this PR appears to bring unrelated `test/data-visual` changes, and found an invalid anti-update 81183d6fe6003ed312e65664bc8bee6f277768c9 that also removed something from `test/data`. I've reverted that commit in master and github doesn't like that (was hoping it'd be treated like a one-line conflict on the Subproject commit, but nah).

**Comment by talaj** [comment]
@lightmare No problem, it's rebased again. Let's merge it finally.

**Pull request merged**
