### PR TITLE
refactoring group, markers symbolizers to reduce compile time / memory usage

### PR DESCRIPTION
**Pull request by lightmare**
**This is not merge-ready!** I'm putting it up for review, and also because I'm not running some tests locally (e.g. database) and 79 visual tests are consistently failing for me, even at commits for which they all succeeded on travis.

Where possible and convenient, I tried making changes with minimal diff, so that they're easier to follow. Also, if you use `git diff -M` (or `git show -M` on individual commits), you'll see that a lot of code was just moved, most often `.hpp -> .cpp`

I will add separate notes about changes I made to group and markers symbolizer rendering later. There are multiple object life-time changes that might severely affect performance, and I'd like to discuss those and ideally find a good benchmark for each symbolizer class. For now, here's how my compile times dropped.

db9face master a few days back:
```
  12.95s  mem:  898MB [0 page faults]     src/agg/process_group_symbolizer.cpp
  10.75s  mem:  845MB [0 page faults]     src/cairo/process_group_symbolizer.cpp
  13.40s  mem: 1037MB [0 page faults]     src/grid/process_group_symbolizer.cpp
 121.53s  mem: 4361MB [89 page fault]     src/renderer_common/process_group_symbolizer.cpp
 122.81s  mem: 4328MB [80 page fault]     src/agg/process_markers_symbolizer.cpppp
 119.84s  mem: 4290MB [5 page faults]     src/cairo/process_markers_symbolizer.cpp
 120.53s  mem: 4306MB [6 page faults]     src/grid/process_markers_symbolizer.cpp
```

06dc592 this branch's head:
```
   4.93s  mem:  531MB [5 page faults]     src/agg/process_group_symbolizer.cpp
   3.49s  mem:  547MB [0 page faults]     src/cairo/process_group_symbolizer.cpp
   4.57s  mem:  525MB [0 page faults]     src/grid/process_group_symbolizer.cpp
  10.25s  mem:  803MB [1 page faults]     src/renderer_common/render_group_symbolizer.cpp
   8.99s  mem:  630MB [1 page faults]     src/agg/process_markers_symbolizer.cpp
   6.96s  mem:  580MB [0 page faults]     src/cairo/process_markers_symbolizer.cpp
   3.76s  mem:  495MB [0 page faults]     src/grid/process_markers_symbolizer.cpp
 112.30s  mem: 4118MB [0 page faults]     src/renderer_common/render_markers_symbolizer.cpp
   7.57s  mem:  608MB [0 page faults]     src/renderer_common/render_thunk_extractor.cpp
```

### CODE REVIEW

**Comment by springmeyer** [comment]
Those are incredible compile improvements. Can't wait to try this out!

**Comment by springmeyer** [comment]
Building locally I see only 24 visual test failures and no unit test failures:

```
$ make test
Inheriting from mapnik-settings.env
* Starting Mapnik tests
* Running C++ Unit tests...
===============================================================================
All tests passed (22703 assertions in 55 test cases)

* Running standalone C++ tests...
===============================================================================
All tests passed (2 assertions in 1 test case)

===============================================================================
All tests passed (817 assertions in 1 test case)

===============================================================================
All tests passed (4 assertions in 1 test case)

===============================================================================
All tests passed (61 assertions in 1 test case)

* Running visual tests...
..............................................................................................................................................................................................................................................................................................................................✘...✘..✘....✘...✘......✘...✘.......✘......✘...✘.....✘.........✘....✘......✘.........✘.........✘.......✘.........✘...............✘..............✘.........✘......✘...........✘...............✘...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Visual rendering: 24 failed / 2710 passed / 0 overwritten / 0 errors
View failure report at "/tmp/mapnik-visual-images/visual-test-results/index.html"
make: *** [test] Error 24
```

The visual test failures are restricted to the `group-symbolizer-line-*` tests. Looks related to a shields going missing.

**Comment by springmeyer** [comment]
This fixes all test failures for me:

```diff
diff --git a/include/mapnik/renderer_common/render_thunk_extractor.hpp b/include/mapnik/renderer_common/render_thunk_extractor.hpp
index fba63e4..1a081af 100644
--- a/include/mapnik/renderer_common/render_thunk_extractor.hpp
+++ b/include/mapnik/renderer_common/render_thunk_extractor.hpp
@@ -78,7 +78,6 @@ struct render_thunk_extractor
     }
 
 private:
-    void extract_text_thunk(text_symbolizer const& sym) const;
 
     box2d<double> & box_;
     render_thunk_list & thunks_;
diff --git a/src/renderer_common/render_thunk_extractor.cpp b/src/renderer_common/render_thunk_extractor.cpp
index 96208e5..3dfe736 100644
--- a/src/renderer_common/render_thunk_extractor.cpp
+++ b/src/renderer_common/render_thunk_extractor.cpp
@@ -98,15 +98,24 @@ void render_thunk_extractor::operator()(markers_symbolizer const& sym) const
 
 void render_thunk_extractor::operator()(text_symbolizer const& sym) const
 {
-    extract_text_thunk(sym);
-}
+    auto helper = std::make_unique<text_symbolizer_helper>(
+        sym, feature_, vars_, prj_trans_,
+        common_.width_, common_.height_,
+        common_.scale_factor_,
+        common_.t_, common_.font_manager_, *common_.detector_,
+        clipping_extent_, agg::trans_affine::identity);
 
-void render_thunk_extractor::operator()(shield_symbolizer const& sym) const
-{
-    extract_text_thunk(sym);
+    double opacity = get<double>(sym, keys::opacity, feature_, common_.vars_, 1.0);
+    composite_mode_e comp_op = get<composite_mode_e>(sym, keys::comp_op, feature_, common_.vars_, src_over);
+    halo_rasterizer_enum halo_rasterizer = get<halo_rasterizer_enum>(sym, keys::halo_rasterizer, feature_, common_.vars_, HALO_RASTERIZER_FULL);
+
+    text_render_thunk thunk(std::move(helper), opacity, comp_op, halo_rasterizer);
+    thunks_.push_back(std::make_unique<render_thunk>(std::move(thunk)));
+
+    update_box();
 }
 
-void render_thunk_extractor::extract_text_thunk(text_symbolizer const& sym) const
+void render_thunk_extractor::operator()(shield_symbolizer const& sym) const
 {
     auto helper = std::make_unique<text_symbolizer_helper>(
         sym, feature_, vars_, prj_trans_,
```

**Comment by lightmare** [comment]
Damn those two were identical, I swear I even took them out and vimdiff'd them :telescope: Now I see the difference is `text_symbolizer_helper` constructor is overloaded for text/shield :wink:

**Comment by springmeyer** [comment]
Overall compile times with `time make`:

refactor-symbolizers
```
real    10m26.622s
user    42m27.817s
sys 1m17.188s
```

master
```
real	14m45.111s
user	46m54.000s
sys	1m20.069s
```

```
$ echo $JOBS
8
```

**Comment by springmeyer** [comment]
For reference I also compiled the spirit-x3 branch from scratch and saw no significant speedups:

```
real	14m26.833s
user	46m56.825s
sys	1m17.847s
```

**Comment by springmeyer** [comment]
@lightmare - anything you see that is needed before this can land?

**Comment by lightmare** [comment]
Just some quick notes:
- this doesn't touch grammars, only rendering, so is shouldn't conflict with anything in `spirit-x3`
- I'm writing a lengthy explanation of these changes right now, for future reference, because when someone asks why or how this was done, in a few months I won't have an idea :thought_balloon: 
- in particular, I feel I have to write down and point out important svg markers changes

**Comment by lightmare** [comment]
The idea is that `src/{agg,cairo,grid,renderer_common}/process_markers_symbolizer.cpp` each instantiated a *huge* function template [render_markers_symbolizer](https://github.com/mapnik/mapnik/blob/db9facef9044e21521610b6299a196af2e1305fd/include/mapnik/renderer_common/process_markers_symbolizer.hpp#L249).
Similarly with `src/{agg,cairo,grid}/process_group_symbolizer.cpp` and 
 [render_group_symbolizer](https://github.com/mapnik/mapnik/blob/db9facef9044e21521610b6299a196af2e1305fd/include/mapnik/renderer_common/process_group_symbolizer.hpp#L240). I decided to get rid of the template arguments, so that these functions are only compiled once, in their own source file.

`render_group_symbolizer<F>` was smaller and had only one template parameter, essentially a callback type, so it was pretty straightforward. I roughly described the process in https://github.com/mapnik/mapnik/issues/2775#issuecomment-173053447 (that was before the implementation in this pull). Now when calling `render_group_symbolizer`, instead of passing an arbitrary function/lambda expression `F render_thunks`, you need to pass a reference to (a descendant of) [render_thunk_list_dispatch](https://github.com/lightmare/mapnik/commit/0dcefeb82a4e73421806c1830eb532f1fb9a1a25#diff-987be0f093e7d1deeba3ddfc3e4d9a05R35).

`render_markers_symbolizer<VD, RD, RendererType, ContextType>` was more difficult, however. `VD/RD` were classes implementing the "how to" render vector/raster markers, respectively, and `ContextType` was used to pass stuff down to their constructors. So I created an abstract base class [markers_renderer_context](https://github.com/lightmare/mapnik/commit/bab9d257747c0a96292b43949d23cd6e950e6954#diff-104ccc7643f5bc7cdd5c82d1fd6a408cR87) with virtual methods for rendering vector/raster markers. Obviously an instance of a derived class needs to be constructed before the call, and whatever `ContextType` carried can go right into it. But there was a catch: in the template version, either `VD` or `RD` instance was constructed inside `render_markers_symbolizer` when the marker type was already known, so they could construct marker-specific stuff.

For example with `svg_marker`, the template version worked like this:
- `render_markers_symbolizer<aggVD, aggRD, RendererType, ContextType>`
   - constructs `render_marker_symbolizer_visitor<aggVD, aggRD, RendererType, ContextType>`
      - constructs `aggVD` (which constructs `SvgRenderer` as its member)
      - calls [baseVD::add_path](https://github.com/mapnik/mapnik/blob/db9facef9044e21521610b6299a196af2e1305fd/include/mapnik/marker_helpers.hpp#L72) via [apply_markers_multi](https://github.com/mapnik/mapnik/blob/db9facef9044e21521610b6299a196af2e1305fd/include/mapnik/marker_helpers.hpp#L186)
         - calls [aggVD::render_marker](https://github.com/mapnik/mapnik/blob/db9facef9044e21521610b6299a196af2e1305fd/src/agg/process_markers_symbolizer.cpp#L98) in a loop, reusing the `SvgRenderer` member

In my non-template version:
- `render_markers_symbolizer(..., agg_markers_renderer_context(...))`
   - constructs `render_marker_symbolizer_visitor<baseVD, baseRD, RendererType, markers_renderer_context&>`
      - constructs `baseVD` (which doesn't construct `SvgRenderer`)
      - calls [baseVD::add_path](https://github.com/lightmare/mapnik/blob/bab9d257747c0a96292b43949d23cd6e950e6954/include/mapnik/marker_helpers.hpp#L123) via `apply_markers_multi`
         - calls [agg_markers_renderer_context::render_marker](https://github.com/lightmare/mapnik/blob/bab9d257747c0a96292b43949d23cd6e950e6954/src/agg/process_markers_symbolizer.cpp#L85) in a loop, constructing a temporary SvgRenderer each time

So this is one big change: not reusing SvgRenderer for multiple placements.

Another is that I moved all the `get<T, keys::stuff>` calls from `add_path` to constructors (wrapped in [struct markers_dispatch_params](https://github.com/lightmare/mapnik/blob/bab9d257747c0a96292b43949d23cd6e950e6954/include/mapnik/marker_helpers.hpp#L51)) - this may be a good thing if `add_path` is called multiple times; or a bad thing if `add_path` is not called at all - honestly I have no idea what is more likely.

Related to the above is a change of two references in [markers_placement_params](https://github.com/lightmare/mapnik/commit/bab9d257747c0a96292b43949d23cd6e950e6954#diff-75a25cbb236cc9337dd79798965ea3d1R41) into regular copies. This structure is not copied, so I assumed the growth wouldn't hurt. And it allowed me to store re-centered transformation matrix (`vector_markers_dispatch`) or synthesized bounding box (`raster_markers_dispatch`) in there.

**Pull request merged**
