### PR TITLE
Handle bounds reprojections which cross the anti-meridian

### PR DESCRIPTION
**Pull request by rcoup**
Fixes the bug identified in #2648 with the simplest solution.

When doing an envelope-points reprojection *to* a geographic coordinate system, generate the points in clockwise order, and after projection check the points are still in clockwise order. If not, expand the resulting bounds to include the world width (±180°). This won't perform any worse for most cases (and we avoid even doing the is-clockwise calc for non-geographic CS), but will be correct.

When mapnik supports multiple boxes for querying, or a concept of geographic Box2d, we can revisit and easily make it better.

### CODE REVIEW

**Comment by springmeyer** [comment]
Want to add some visual tests with small but representative sample data? This would be a nice redundancy and help give a visual sense of problems if this were to ever regress.

**Comment by rcoup** [comment]
@springmeyer I added a visual test based on @craigds' data. Any idea why cairo would still show the error after the fix - does it do additional/different bounds handling somewhere? agg/grid are fine.

If you're free to jump on IRC for a couple of minutes it'd be handy :)

**Comment by rcoup** [comment]
Outcome of test weirdness: visual test comparator is not finding any differences between (clearly different) broken & reference images for cairo, but the renderer is generating the right output.

**Comment by springmeyer** [comment]
@rcoup replicated and fixed the cairo visual test oddity (should now fail when it should): https://github.com/mapnik/mapnik/commit/d38b3bb2cf7f84e871bed897d43d0142eaff7d5c

**Pull request merged**
