### PR TITLE
better handling of missing styles

### PR DESCRIPTION
**Pull request by talaj**
Refs https://github.com/mapnik/mapnik/issues/2822.

* `MAPNIK_LOG_DEBUG` raised to `MAPNIK_LOG_ERROR` for the message during rendering.
* Throws during xml parsing when `strict = true`.

### CODE REVIEW

**Comment by talaj** [comment]
Travis fails because https://github.com/mapnik/test-data-visual/pull/9 is not merged.

**Comment by artemp** [comment]
@talaj - I'm getting 
```
ERROR (Unable to process some data while parsing 'test/data-visual/styles/marker-on-line-svg-no-box.xml': Style 'gamma' required for layer 'layer'.)
```

**Comment by talaj** [comment]
Reference to git submodule with visual test data is not updated. Will do.

**Comment by talaj** [comment]
Updated, should be all green now.

**Pull request merged**
